name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jacobcrabill/alpine-zig:0.14.0

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Build
        run: zig build test
